# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 433feef1326d8d73b6d6a2e7cdbfd7b5857b569139255ddd63c972ca216c4ceb448e050f79532e08360c85469b81ffa7f45a91e47d0f73d8e9a54a7d2111d6fb

test:
  secret_key_base: 7eba2f022e85bc673b6ed99cf7055a198fdf754d7f8d0c4bad72cab049bafd1913eeb9179c59e46211a03d561a55a8f559daf283732186aef21ad13594d5dc8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
